---

- name: Install docker py
  apt: name=python-docker state=present
  when: DOCKER_LOGIN_SERVICE is defined

- name: Prune unused images
  command: docker image prune -af
  become: true

- name: Create Compose Foldder
  file:
    name: "{{ DOCKER_COMPOSE_WORKDIR }}"
    state: directory

- name: Copy context
  template:
    src: "{{ DOCKER_COMPOSE_FILE }}"
    dest: "{{ DOCKER_COMPOSE_WORKDIR }}/docker-compose.yml"
  when: DOCKER_COMPOSE_FILE is defined

- name: Create env file
  template:
    src: vars.env
    dest: "{{ DOCKER_COMPOSE_WORKDIR }}/.env"
- name: Log into
  docker_login:
    username: "{{ DOCKER_LOGIN_USERNAME }}"
    password: "{{ DOCKER_LOGIN_PASSWORD }}"
    registry_url: "{{ DOCKER_LOGIN_SERVICE }}"
  when: DOCKER_LOGIN_SERVICE is defined

- name: Pull images
  command: docker-compose pull
  args:
    chdir: "{{ DOCKER_COMPOSE_WORKDIR }}"

- name: Logout from docker
  command: docker logout "{{ DOCKER_LOGIN_SERVICE }}"
  when: DOCKER_LOGIN_SERVICE is defined

- name: Copy systemd files
  template:
    src: service.unit
    dest: /etc/systemd/system/{{ DOCKER_COMPOSE_APP_NAME }}.service

- name: Reload
  command: systemctl daemon-reload

- name: enable services
  service: name={{ DOCKER_COMPOSE_APP_NAME }}.service enabled=yes state=restarted
